services:
  advisor_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-trip-advisor:latest
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY
