name: CI Pipeline

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test:
    name: Run Tests and Docker Compose
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.8
        options: --privileged # Needed to run Docker inside Docker
        ports:
          - 8000:8000
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run Pytest
      run: |
        pytest

    - name: Set up Docker Compose
      run: |
        docker-compose up -d --build
        sleep 10 # Wait for services to be fully up
        docker-compose down

    - name: Post Test Cleanup
      if: always()
      run: docker-compose down